import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

test("MDStudio unifies the existing PicoCalc project workflow", () => {
  const studio = fs.readFileSync(path.resolve("tools/picocalc/mdstudio.sh"), "utf8");
  const step = fs.readFileSync(path.resolve("tools/picocalc/genesis-step.sh"), "utf8");
  assert.match(studio, /^#!\/bin\/bash/);
  assert.match(studio, /Mega Drive Lua Studio/);
  assert.match(studio, /1  Edit code \(Ctrl\+X returns\)/);
  assert.match(studio, /2  Check project/);
  assert.match(studio, /4  Build and run/);
  assert.match(studio, /5  API help/);
  assert.match(studio, /7  Project information/);
  assert.match(studio, /9  Project assets/);
  assert.match(studio, /N  New project/);
  assert.match(studio, /O  Open project/);
  assert.match(studio, /IFS= read -e -r open_name/);
  assert.match(studio, /IFS= read -e -r asset_path/);
  assert.match(studio, /cd "\$project_directory"/);
  assert.match(studio, /read_asset_path 'Existing asset path: '/);
  assert.match(studio, /read_asset_path "Existing \$asset_type path: "/);
  assert.match(studio, /open_name=\$\{open_name%\/\}/);
  assert.match(studio, /node "\$sdk\/bin\/mdlua\.js" init "\$new_name"/);
  assert.match(studio, /\[ ! -f "\$projects_root\/\$open_name\/mdlua\.json" \]/);
  assert.match(studio, /exec "\$0" "\$open_name"/);
  assert.match(studio, /exec "\$0" "\$new_name"/);
  assert.match(studio, /project_command set/);
  assert.match(studio, /project_command unset/);
  assert.match(studio, /project_command add/);
  assert.match(studio, /project_command remove/);
  assert.match(studio, /8  Inspect sprite sheet/);
  assert.match(studio, /9  Inspect tile map/);
  assert.match(studio, /inspect_command sheet/);
  assert.match(studio, /inspect_command map/);
  assert.match(studio, /10 Visual sprite-sheet preview/);
  assert.match(studio, /11 Visual tile-map preview/);
  assert.match(studio, /14 Audition music and SFX/);
  assert.match(studio, /12 Inspect audio assets/);
  assert.match(studio, /13 Inspect sprite variants/);
  assert.match(studio, /MDLUA_NATIVE_TOOLCHAIN/);
  assert.match(studio, /mdlua\.js" preview sheet/);
  assert.match(studio, /mdlua\.js" preview map/);
  assert.match(studio, /mdlua\.js" preview audio/);
  assert.match(studio, /picodrive-native\/run\.sh/);
  assert.match(studio, /cd "\$\(dirname "\$manifest"\)"/);
  assert.match(studio, /PIPESTATUS\[0\]/);
  assert.match(studio, /native PicoCalc toolchain/);
  assert.match(studio, /if ! IFS= read -r choice; then/);
  assert.match(studio, /project_args=\(\)/);
  assert.match(studio, /MDSTUDIO_LAST_PROJECT:-\/home\/pico\/\.mdstudio-last-project/);
  assert.match(studio, /\[ -f "\$remembered_project\/mdlua\.json" \]/);
  assert.match(studio, /project_label=\$\(basename "\$remembered_project"\)/);
  assert.match(studio, /mv "\$last_project_tmp" "\$last_project_file"/);
  assert.match(studio, /check "\$\{project_args\[@\]\}"/);
  assert.match(studio, /mdapi-browser\.mjs/);
  assert.match(studio, /genesis-step\.sh/);
  assert.match(studio, /mdedit-session\.sh/);
  assert.match(step, /check\)/);
  assert.match(step, /node bin\/mdlua\.js check --project/);
});
