// build-md.mjs — mdlua's build orchestrator (spike slice).
//
// Lua -> compile() (the shared PICO-8-dialect front-end + md emitter) -> C
// -> buildGenesisC() (romdev-toolchain-m68k-gcc, the published pipeline)
// -> finalizeGenesisRom() (pad + $18E checksum; REQUIRED for strict loaders)
// -> .bin
//
// Unlike gbalua there is NO romdevtools resolution dance: the driver ships in
// the pinned toolchain package (0.3.0) — the day-one dependency graph is the
// final one.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildGenesisC, finalizeGenesisRom, parseBuildLog, shareDir } from "romdev-toolchain-m68k-gcc";
import { assertOutputDistinct } from "./output-path.mjs";
import { bitmapTimingSource } from "./bitmap-timing.mjs";
import { compile, formatDiagnostics } from "./index.js";
import { sheetAssetsHeader, mapAssets, scaledSheetAssets, flagsAssetHeader } from "./asset-headers.mjs";
import { ssprEmitter, variantEmitter } from "./sprite-variants.mjs";
import { BUILTINS } from "./builtins.js";
import { wavToXgm2Pcm, songToXgm2, songsBankC, sfxBankC, isGzip } from "./audio-assets.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SDK_DIR = path.resolve(__dirname, "..", "md-sdk");

/**
 * Build a mdlua game to a Genesis .bin.
 * @param {string} entryLua  path to main.lua
 * @param {string} outPath   path for the finished ROM
 * @param {object} [opts]
 * @returns {Promise<{ok:boolean, outPath:string, log:string}>}
 */
// --sheet/--map PNGs -> the generated md_assets.h (or stubs when absent).
async function buildAssetsHeader(opts) {
  let scaling = { header: "", report: { variants: [], bytes: 0, sheetBytes: 0 } };
  if (opts.spriteVariantsPath && !opts.sheetPath) throw new Error("--sprite-variants requires --sheet");
  let mapTiles = 0;
  let h = "// generated by build-md — asset data for this build\n";
  if (opts.gffPath) h += flagsAssetHeader(await readFile(opts.gffPath));
  if (opts.sheetPath) {
    h += "#define MD_HAVE_SHEET 1\n";
    const png = await readFile(opts.sheetPath);
    h += sheetAssetsHeader(png, path.basename(opts.sheetPath), "sheet");
    scaling = scaledSheetAssets(png, opts.spriteVariantsPath ? JSON.parse(await readFile(opts.spriteVariantsPath, "utf8")) : { variants: [] });
    h += scaling.header;
  }
  if (opts.mapPath) {
    h += "#define MD_HAVE_MAP 1\n";
    const map = mapAssets(await readFile(opts.mapPath), path.basename(opts.mapPath));
    h += map.header;
    mapTiles = map.tileCount;
  }
  const sheetTiles = opts.sheetPath ? scaling.report.sheetBytes / 32 : 4;
  const variantTiles = scaling.report.bytes / 32;
  const totalTiles = sheetTiles + mapTiles + variantTiles;
  // Default pinned SGDK layout; the C guard remains the authority on overflow.
  const capacityTiles = 1424;
  return { header: h, scaling: scaling.report,
    graphics: { sheetTiles, mapTiles, variantTiles, totalTiles, capacityTiles,
      freeTiles: capacityTiles - totalTiles, bytes: totalTiles * 32,
      fallbackSheet: !opts.sheetPath } };

}

// (wavToXgm2Pcm and the bank C generators live in audio-assets.mjs — the
// BROWSER-SAFE module both this CLI and the web IDE pipeline import, so the
// generated C is identical on every host.)

export async function buildMd(entryLua, outPath, opts = {}) {
  const inputs = [entryLua, opts.sheetPath, opts.mapPath, opts.gffPath,
    opts.spriteVariantsPath, ...(opts.sfxPaths ?? []), ...(opts.musicPaths ?? [])];
  await assertOutputDistinct(outPath, inputs);
  const src = await readFile(entryLua, "utf8");
  const assets = await buildAssetsHeader(opts);
  // num8 (8.8): emit supports it; the RUNTIME does not yet (16.16 sin table,
  // time, print_num). Wire the flag only when md_math grows -DMD_NUM8 paths -
  // shipping it now would be silently wrong math. (68000 is 16-bit-native, so
  // num8 is worth measuring in the Phase-3 perf pass.)
  const variants = assets.scaling.variants;
  const res = compile(src, path.basename(entryLua), { target: "md", builtins: {
    ...BUILTINS,
    sspr: { ...BUILTINS.sspr, emit: ssprEmitter(variants, assets.scaling.sheetWidth ? [assets.scaling.sheetWidth, assets.scaling.sheetHeight] : null) },
    ssprv: { ...BUILTINS.ssprv, emit: variantEmitter(variants) },
  } });
  if (variants.length && /\b(?:md_(?:pset|pget|line|rect|rectfill|circ|circfill)|BMP_\w+)\(/.test(res.c ?? "")) {
    throw new Error("pre-scaled sprite variants cannot share VRAM with bitmap drawing; use the hardware sprite/tile path");
  }
  const diagnostics = res.diagnostics.map(d => ({ ...d, file: path.resolve(entryLua) }));
  const warnings = diagnostics.filter((d) => d.severity === "warning");
  if (warnings.length) process.stderr.write(formatDiagnostics(warnings) + "\n");
  if (!res.ok) {
    const errs = diagnostics.filter((d) => d.severity === "error");
    throw new Error("mdlua: compile failed\n" + formatDiagnostics(errs));
  }

  const rd = (f) => readFile(path.join(SDK_DIR, f), "utf8");
  const sources = {
    "main.c": res.c,
    "md_api.c": await rd("md_api.c"),
    "md_math.c": await rd("md_math.c"),
    "md_anim.c": await rd("md_anim.c"),
  };
  const headers = {
    "md_api.h": await rd("md_api.h"),
    "md_math.h": await rd("md_math.h"),
    "md_sintab.h": await rd("md_sintab.h"),
    "md_font.h": await rd("md_font.h"),
    "md_assets.h": assets.header,
  };
  // Compile our checked timing adaptation instead of the archive's BMP object.
  sources["md_bmp.c"] = bitmapTimingSource(await readFile(path.join(shareDir, "lib", "sgdk", "src", "bmp.c"), "utf8"));

  // Song bank: --music a.vgm,b.vgm[,c.xgc] -> compiled XGM2 blobs, bank order
  // = music(n) index. .vgm converts via romdev-xgm2 (byte-identical to SGDK's
  // xgm2tool - verified against demo.xgc), .vgz inflates here (node side; the
  // browser IDE inflates with DecompressionStream before calling songToXgm2),
  // .xgc passes through. No --music but the game calls music() -> the SGDK
  // demo tune as a 1-song bank, so first-run sound Just Works.
  const usesMusic = /\bmd_music\b/.test(res.c);
  const songBlobs = [];
  if (opts.musicPaths && opts.musicPaths.length) {
    const { gunzipSync } = await import("node:zlib");
    for (const p of opts.musicPaths) {
      let bytes = new Uint8Array(await readFile(p));
      if (isGzip(bytes)) bytes = new Uint8Array(gunzipSync(bytes));
      songBlobs.push(songToXgm2(bytes));
    }
  } else if (usesMusic) {
    const { shareDir } = await import("romdev-toolchain-m68k-gcc");
    songBlobs.push(new Uint8Array(await readFile(path.join(shareDir, "lib", "sgdk", "music", "demo.xgc"))));
  }
  sources["md_songs.c"] = songsBankC(songBlobs);

  // PCM SFX bank: --sfx a.wav,b.wav -> 8-bit signed 13.3kHz samples, 256-byte
  // aligned + padded (the XGM2 PCM contract). Stub table when absent.
  const sfxBlobs = [];
  for (const p of opts.sfxPaths ?? []) {
    sfxBlobs.push(wavToXgm2Pcm(new Uint8Array(await readFile(p))));
  }
  sources["md_sfx_data.c"] = sfxBankC(sfxBlobs);

  const r = await buildGenesisC({ sources, headers, sgdk: true });
  if (!r.ok) {
    const errors = parseBuildLog(r.log).filter((issue) => issue.severity === "error");
    const detail = errors.map((e) => `${e.file ?? r.stage}${e.line ? `:${e.line}` : ""}: ${e.message}`).join("\n") || r.log.slice(-2000);
    throw new Error(`mdlua: ${r.stage} failed\n${detail}`);
  }
  const rom = finalizeGenesisRom(r.binary);
  await mkdir(path.dirname(path.resolve(outPath)), { recursive: true });
  await assertOutputDistinct(outPath, inputs);
  await writeFile(outPath, rom);
  return { ok: true, outPath, log: r.log, spriteVariants: assets.scaling, graphics: assets.graphics };
}
